TrajectoryPlannerROS:
  ack_vel_max:  0.4
  ack_vel_min: -0.4
  ack_acc_max:  1.0
  ack_steer_angle_max:  0.35
  ack_steer_angle_min: -0.35
  ack_steer_speed_max:  0.5
  ack_steer_speed_min: -0.5
  ack_steer_acc_max:    1.0
  ack_axis_distance:    1.65

  sim_time:                10
  sim_granularity:         0.025
  angular_sim_granularity: 0.025

  pdist_scale:   1.0
  gdist_scale:   0.8
  occdist_scale: 1.0
  hdist_scale:   1.0

  heading_points:  8
  vx_samples:     11
  vtheta_samples: 20

  simple_attractor: false

  xy_goal_tolerance:  0.5
  yaw_goal_tolerance: 3.14