#map_type: costmap
transform_tolerance: 0.2
obstacle_range:     10.0
raytrace_range:     12.0
inflation_radius:    2.4
robot_radius:        1.5
#footprint: [[2.0, 1.6], [2.0, -1.6], [-0.4, -1.6], [-0.4, 1.6]]
footprint: [[2.0, 0.6], [2.0, -0.6], [-0.4, -0.6], [-0.4, 0.6]]

observation_sources: base_scan

base_scan: {sensor_frame:            base_scan_link,
            data_type:               LaserScan,
            topic:                   /base_scan/scan,
            expected_update_rate:    0, #1.5,
            observation_persistence: 0.0,
            marking:                 true,
            clearing:                true,
            min_obstacle_height:    -0.10,
            max_obstacle_height:     2.0}
